name: Generate a build and push to another branch

on:
  push:
    branches:
      - Desarrollo  # Cambia esto por la rama que deseas usar

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push
    permissions:
      contents: write  # Otorga permisos de escritura al GITHUB_TOKEN
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Git identity
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Install all dependencies
        run: npm install

      - name: Build
        run: npm run build  # Genera los archivos en dist/inventario

      - name: Create or reset build branch
        run: |
          git checkout --orphan temp-build  # Crea una rama huérfana temporal
          git add -A  # Agrega todos los archivos
          git commit -m "Initial commit"  # Crea un commit vacío
          git branch -D build  # Elimina la rama build local si existe
          git branch -m build  # Renombra la rama temporal a build
          git push origin --delete build  # Elimina la rama build remota si existe
          git push origin build  # Sube la nueva rama build

      - name: Move files to root
        run: |
          mv dist/inventario/* .  # Mueve los archivos generados a la raíz
          rm -rf dist  # Elimina la carpeta dist

      - name: Push build to branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: build
          FOLDER: .
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Build generado el {date} desde {sha}"
          FORCE_PUSH: true  # Forzar el push